name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout country-flags repo
        uses: actions/checkout@v4
        with:
          repository: hampusborgos/country-flags
          path: target/country-flags
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Check fmt
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run ignored tests
        run: cargo test -- --ignored
