name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout country-flags repo
        uses: actions/checkout@v2
        with:
          repository: hjnilsson/country-flags
          path: target/country-flags
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Check fmt
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run ignored tests
        run: cargo test -- --ignored

  image-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Print make version
        run: make --version
      - name: Run make check
        run: make check
      - name: Build image
        run: make image

  image-static-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Print make version
        run: make --version
      - name: Run make check
        run: make check
      - name: Build static image
        run: make image-static
