name: Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Print make version
        run: make --version
      - name: Run make check
        run: make check
      - name: Login to ghcr
        run: buildah login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Build image
        run: make image

  image-static:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Print rust version
        run: rustc --version --verbose && cargo --version
      - name: Print make version
        run: make --version
      - name: Run make check
        run: make check
      - name: Login to ghcr
        run: buildah login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Build static image
        run: make image-static

  run-image:

    runs-on: ubuntu-latest
    needs: image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run image
        run: make run-image

  run-image-static:

    runs-on: ubuntu-latest
    needs: image-static

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run static image
        run: make run-image-static
